### ISSUE TITLE
Migration fails 

### ISSUE THREAD

**Issue by andistuder** [FundingCircle/shipment_tracker#16]
Running migrations form an empty database fails. 

```ruby 
rake aborted!
NameError: uninitialized constant RenameRepositoriesToRepositoryLocations
```

```ruby 
rake aborted!
NameError: uninitialized constant AddRemoteHeadToRepositoryLocations
```

RenameRepositoriesToRepositoryLocations
```ruby
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant Events::Base/Users/andi/Development/shipment_tracker/db/migrate/20150507103704_rename_events.rb:13:in `block in up'
```

I believe these error where introduced in the two commits where migrations where edited: 
https://github.com/FundingCircle/shipment_tracker/commit/f50b6f212a0c6d1ba47ba2cda10f02a10d5f0e6c
https://github.com/FundingCircle/shipment_tracker/commit/35d677af9514dbb8b4ee80ebad8353ae298616d6

I opened a PR with a suggested fix https://github.com/FundingCircle/shipment_tracker/pull/17

**Comment by fundingcircleaudit** [comment]
solved

**Comment by sgerrand** [comment]
@fundingcircleaudit: Not sure you should be logged into the web UI. :person_with_pouting_face:

**Comment by andistuder** [comment]
@sgerrand my fault. I had to log in to issue a token... and forgot to switch account. AFAIK the comment above is the only action I've taken as @fundingcircleaudit
