### ISSUE TITLE
Unlink tickets from a Feature Review

### ISSUE THREAD

**Issue by dideler** [FundingCircle/shipment_tracker#180]
> As a Developer offering a feature for review
> I want to unlink a ticket from a Feature Review
> Because the ticket was accidentally linked

Clicking the :x: button next to a ticket on a Feature Review deletes the row and unlinks the ticket.

Requires deleting comments via JIRA API.

Deleting a comment would be best achieved by using the Jira Comment ID. This is not currently stored. We need to add a `comment_id` column to the database and then use that comment ID to call the Jira delete comment API.

Edit: [Workaround until this is implemented](https://github.com/FundingCircle/shipment_tracker/wiki/FAQ#how-do-i-unlink-a-ticket)

**Comment by Pryowin** [comment]
This is needed
We are having to exert significant effort working around this limitation.

**Comment by damien** [comment]
@Pryowin and I ran face first into this today: I had mistakenly cross referenced a ticket that spanned multiple PRs and I had no way of correcting the feature/ticket linkages when it came time to deploy.

**Comment by iiyq** [comment]
This would make scheduling deploys much easier

**Comment by MiroslavCsonka** [comment]
Closed by https://github.com/FundingCircle/shipment_tracker/pull/192
