### ISSUE TITLE
Deploy tagged releases

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/shipment_tracker#19]
Consider tagging releases for this project as part of deployment. It's helpful in determining what features are currently running in production.

**Comment by dideler** [comment]
Another way to see what's running in production (and what will soon be) is the Releases page for Shipment Tracker. \<shipment tracker url\>/releases/shipment_tracker

**Comment by LogaJ** [comment]
Closed as we've updated the Readme to metion where release info is stored.
