### ISSUE TITLE
Images for GitHub wiki

### ISSUE THREAD

**Issue by andistuder** [FundingCircle/shipment_tracker#42]
This issue is opened, so we can host images for the Wiki. To host an image, add/edit a comment and include an image. Then grab the image URI and include in the Wiki.

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390164/cbbb4204-6e6e-11e5-9f06-6a90e2d4c3ec.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390218/101352f2-6e6f-11e5-894a-18df47305e6e.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390235/3a9a6e02-6e6f-11e5-9892-e93c59014a1e.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390314/b9dac57c-6e6f-11e5-9792-7ba1871ea757.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390327/d3497df0-6e6f-11e5-92d8-0e3c5c6fe86d.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390389/3e1cf8fa-6e70-11e5-99d3-3516944ab66a.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390435/89a67c24-6e70-11e5-823c-7bfd915ccd62.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390499/edb95934-6e70-11e5-8aa3-5f4584dec785.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390524/1957c2f6-6e71-11e5-8628-ef2d025cbc31.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390547/3f07917a-6e71-11e5-96e1-c2184ec2aa21.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390556/63a75e66-6e71-11e5-8803-15fc018b07be.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390592/988fca8c-6e71-11e5-9a6d-ad60816e2b97.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390618/ade9d382-6e71-11e5-9bd5-f3430968f6bc.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390634/d97b9a94-6e71-11e5-8f9c-52aa072b26b1.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10390676/18eea888-6e72-11e5-9511-70951554f41c.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10391104/98f2c59e-6e74-11e5-9a92-3e61665305d2.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10394360/b71dc98c-6e8e-11e5-9b90-840f43e4587c.png)

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10394387/ee7cac90-6e8e-11e5-8903-a46d9666408d.png)

**Comment by dideler** [comment]
Closing as this "issue" doesn't need to be open to host the images. Carry on adding images as needed.

**Comment by chriswan84** [comment]
![image](https://cloud.githubusercontent.com/assets/14111432/10851954/f0bef9ac-7f25-11e5-892e-9a28a1c30417.png)

**Comment by dideler** [comment]
![screenshot 2016-04-05 14 09 08](https://cloud.githubusercontent.com/assets/497458/14282808/ff5d26bc-fb37-11e5-8009-411ecb3908bc.png)
