### ISSUE TITLE
Redirect to originally requested location after login

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/shipment_tracker#7]
```cucumber
Given I am not logged in
And I am able to login
And I go to a URL that requires authentication
When I login successfully 
Then I should be redirected to the URL I originally entered
```

**Comment by sgerrand** [comment]
Ping @FundingCircle/black-bat for :thought_balloon:s.

**Comment by andistuder** [comment]
Yes, that would definitely be a improvement. I believe we classed it as a 'nice to have' when we had to introduce authentication, but we should re-consider this. 

I've added a Jira ticket to our backlog, for consideration by @whamilton42 
https://jira.fundingcircle.com/browse/ENG-208

**Comment by sgerrand** [comment]
@andistuder: :kissing_cat:

**Comment by dideler** [comment]
Added in 586b91c751f200ecb3723cd3b31e0fc7de1e7c1c
