### ISSUE TITLE
Cannot view release list for an application

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/shipment_tracker#9]
When I try to display releases by application, e.g. for [alpaca](https://shipment-tracker.fundingcircle.co.uk/releases/alpaca) or [shipment_tracker](https://shipment-tracker.fundingcircle.co.uk/releases/shipment_tracker), the Rails application does not respond in time and I see a default "502 Bad Gateway" page returned by Nginx.

**Comment by dideler** [comment]
Timeouts are happening in production unfortunately because we haven't done any performance improvements (such as snapshotting) for this projection yet. We have a story in our current sprint for this so hopefully we can fix it soon.

**Comment by dideler** [comment]
@sgerrand We've recently done some work around Releases (and there's still some more to be done). All the repos for that page should load now except for fca (page load currently grows linearly with commits, and fca has a lot of commits).

**Comment by sgerrand** [comment]
:+1:
